sonar:
  stage: analysis
  script:
  - bash ci.sh analysis
#  - echo "Skip this step just !!!!"

before_script:
- export BUILD_SITE=true
- export BUILD_TEST_SKIP=true
- export LIB_CI_SCRIPT=http://gitlab.td.internal/home1-oss/oss-build/raw/develop/src/main/ci-script/lib_ci.sh
- export ORIGIN_REPO_SLUG=SPEC/factor-calculate-test
- export INFRASTRUCTURE=internal
- export INTERNAL_INFRASTRUCTURE_CONF_GIT_PREFIX=http://gitlab.td.internal/
- export INTERNAL_NEXUS3=http://nexus.td.internal

on_develop_push:
  dependencies:
  - on_non_release_push
  only:
  - develop
  script:
  - bash ci.sh publish_artifact publish_site
  stage: publish
  artifacts:
    when: on_success
    expire_in: 5 day
    paths:
    - factor-calculate-test/target/*-exec.jar

on_feature_push:
  dependencies:
  - on_non_release_push
  only:
  - /^feature\/.+$/
  script:
  - bash ci.sh publish_artifact
  stage: publish


#on_master_push:
#  dependencies:
#  - on_non_release_push
#  only:
#  - master
#  script:
#  - echo do nothing
#  stage: publish

on_non_release_push:
#  artifacts:
#    when: on_success
#    expire_in: 1 day
#    untracked: true
#    paths:
#    - target/*.tar.gz
#    - target/*.war
  except:
  - /^release\/.+$/
  script:
  - bash ci.sh clean_test_and_build
  stage: build

on_release_push:
  before_script:
  - export BUILD_SITE=true
  - export BUILD_TEST_SKIP=true
  - export LIB_CI_SCRIPT=http://gitlab.td.internal/home1-oss/oss-build/raw/develop/src/main/ci-script/lib_ci.sh
  - export ORIGIN_REPO_SLUG=SPEC/factor-calculate-test
  - export INFRASTRUCTURE=internal
  - export INTERNAL_INFRASTRUCTURE_CONF_GIT_PREFIX=http://gitlab.td.internal/
  - export INTERNAL_NEXUS3=http://nexus.td.internal
  only:
  - /^release\/.+$/
  script:
  - bash ci.sh clean_test_and_build publish_artifact publish_site
  stage: publish


stages:
- build
- analysis
- publish